// frontend/src/pages/Analyser.jsx
// Single Transaction Analyser 
// Multi-step form to score one transaction. Supports:
// - Manual entry across 4 steps
// - Loading real test set samples (10 fraud + 10 legitimate)
// - Algorithm selection via ModelSelector
// - Rich result dashboard with probability, anomaly score, tier

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import axios from 'axios';
import {
  ShieldCheck, AlertOctagon, ArrowRight,
  ArrowLeft, Loader2, RefreshCw, Activity,
  Database, ChevronDown, Cpu
} from 'lucide-react';

// Real test set transactions embedded at build time
// Generated by the notebook cell in Notebook 3
// 10 fraud + 10 legitimate with known ground truth labels
import SAMPLE_TRANSACTIONS from '../sampleTransactions.json';

// Form step configuration 
// Splits 30 features across 4 steps so the form isn't overwhelming
const STEP_CONFIG = [
  {
    title:    'Core Transaction Details',
    subtitle: 'Time and Amount the two raw unmodified features',
    fields:   ['Time', 'Amount']
  },
  {
    title:    'PCA Components — V1 to V7',
    subtitle: 'First 7 principal component features',
    fields:   ['V1','V2','V3','V4','V5','V6','V7']
  },
  {
    title:    'PCA Components — V8 to V14',
    subtitle: 'V14 is the strongest fraud predictor in this model',
    fields:   ['V8','V9','V10','V11','V12','V13','V14']
  },
  {
    title:    'PCA Components — V15 to V28',
    subtitle: 'Final set of principal components',
    fields:   [
      'V15','V16','V17','V18','V19','V20',
      'V21','V22','V23','V24','V25','V26','V27','V28'
    ]
  }
];

// Empty form state template 
const DEFAULT_FORM = {
  Time: '', Amount: '',
  ...Object.fromEntries(
    Array.from({ length: 28 }, (_, i) => [`V${i+1}`, ''])
  )
};

// Framer Motion variants 
const slideVariants = {
  hidden:  { opacity: 0, x: 60 },
  visible: { opacity: 1, x: 0,  transition: { duration: 0.35 } },
  exit:    { opacity: 0, x: -60, transition: { duration: 0.25 } }
};

const resultVariants = {
  hidden:  { opacity: 0, scale: 0.92 },
  visible: { opacity: 1, scale: 1, transition: { duration: 0.4 } }
};

// Confidence tier color config 
const TIER_CONFIG = {
  HIGH:   { color:'text-red-400',    bg:'bg-red-500/10',    border:'border-red-500/30'    },
  MEDIUM: { color:'text-orange-400', bg:'bg-orange-500/10', border:'border-orange-500/30' },
  REVIEW: { color:'text-yellow-400', bg:'bg-yellow-500/10', border:'border-yellow-500/30' },
  CLEAR:  { color:'text-emerald-400',bg:'bg-emerald-500/10',border:'border-emerald-500/30'}
};

export default function Analyser() {
  //  Component state 
  // -- State is local to this page, not needed globally
  const [step, setStep]             = useState(0);
  const [formData, setFormData]     = useState(DEFAULT_FORM);
  const [loading, setLoading]       = useState(false);
  const [result, setResult]         = useState(null);
  const [error, setError]           = useState(null);
  const [selectedSample, setSelectedSample] = useState(null);
  const [showSelector, setShowSelector]     = useState(false);

  // Model selector state
  // Fetched from Flask /api/models on mount
  const [models, setModels]           = useState([]);
  const [selectedModel, setSelectedModel] = useState(null);
  const [showModelPicker, setShowModelPicker] = useState(false);

  const totalSteps = STEP_CONFIG.length;
  const isLastStep = step === totalSteps - 1;

  // Fetch available models on mount 
  useEffect(() => {
    axios.get('http://127.0.0.1:5000/api/models')
      .then(res => {
        setModels(res.data.models || []);
        // Default to the best model AutoGluon identified
        const def = res.data.models?.find(m => m.is_default);
        if (def) setSelectedModel(def);
      })
      .catch(() => {});
  }, []);

  // Input handler 
  const handleChange = e => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  // Load a real test set sample into the form 
  const loadSample = sample => {
    const stringified = Object.fromEntries(
      Object.entries(sample.data).map(([k,v]) => [k, String(v)])
    );
    setFormData(stringified);
    setSelectedSample(sample);
    setShowSelector(false);
    setStep(0);
    setResult(null);
    setError(null);
  };

  // Clear sample and reset form 
  const clearSample = () => {
    setFormData(DEFAULT_FORM);
    setSelectedSample(null);
  };

  // Navigation handlers 
  const next = () => isLastStep ? submit() : setStep(s => s + 1);
  const back = () => setStep(s => s - 1);

  // Full reset to start a new prediction 
  const reset = () => {
    setStep(0);
    setFormData(DEFAULT_FORM);
    setResult(null);
    setError(null);
    setSelectedSample(null);
  };

  // Submit to Flask API for prediction 
  // Converts form strings to floats and attaches model selection
  const submit = async () => {
    setLoading(true);
    setError(null);
    try {
      const numericData = Object.fromEntries(
        Object.entries(formData).map(([k,v]) => [k, parseFloat(v) || 0])
      );

      // Attach the selected model id if user chose one
      // Flask will use this to call predictor.predict(model_name=...)
      if (selectedModel) {
        numericData.selected_model = selectedModel.id;
      }

      const response = await axios.post(
        'http://127.0.0.1:5000/api/predict',
        numericData
      );
      setResult(response.data);
    } catch (err) {
      setError(
        err.response?.data?.error ||
        'Could not connect to the prediction engine. Is Flask running?'
      );
    } finally {
      setLoading(false);
    }
  };

  // Progress bar percentage 
  const progress = ((step + 1) / totalSteps) * 100;

  // Sample lists split by label 
  const fraudSamples = SAMPLE_TRANSACTIONS.filter(
    t => t.label === 'FRAUD'
  );
  const legitSamples = SAMPLE_TRANSACTIONS.filter(
    t => t.label === 'LEGITIMATE'
  );

  return (
    <div className="max-w-2xl mx-auto
                    px-4 sm:px-6 py-16">

      {/* Page header  */}
      <motion.div
        className="text-center mb-10"
        initial={{ opacity:0, y:20 }}
        animate={{ opacity:1, y:0 }}
      >
        <div className="inline-flex items-center gap-2
                       px-4 py-1.5 bg-emerald-500/10
                       border border-emerald-500/30 rounded-full
                       text-emerald-400 text-sm font-medium mb-4">
          <Activity size={14} />
          Live Transaction Scoring
        </div>
        <h1 className="text-3xl sm:text-4xl font-black mb-2">
          Transaction Analyser
        </h1>
        <p className="text-slate-400 text-sm">
          Score a single transaction using the trained ensemble.
          Load a real test sample or enter values manually.
        </p>
      </motion.div>

      {/* Model selector  */}
      {!result && (
        <div className="mb-4">
          <button
            onClick={() => setShowModelPicker(s => !s)}
            className="w-full flex items-center
                       justify-between px-4 py-3
                       bg-slate-800/60 border border-slate-700/50
                       rounded-xl hover:border-purple-500/50
                       transition-all text-slate-300
                       hover:text-white"
          >
            <div className="flex items-center gap-2">
              <Cpu size={16} className="text-purple-400" />
              <span className="text-sm font-medium">
                {selectedModel
                  ? `Model: ${selectedModel.display}`
                  : 'Select algorithm...'
                }
              </span>
            </div>
            <ChevronDown
              size={16}
              className={`transition-transform
                ${showModelPicker ? 'rotate-180' : ''}`}
            />
          </button>

          {/* Model dropdown */}
          <AnimatePresence>
            {showModelPicker && (
              <motion.div
                initial={{ opacity:0, y:-8 }}
                animate={{ opacity:1, y:0 }}
                exit={{ opacity:0, y:-8 }}
                transition={{ duration:0.2 }}
                className="mt-2 bg-slate-800 border
                           border-slate-700 rounded-xl
                           overflow-hidden shadow-2xl"
              >
                {models.length === 0 ? (
                  <p className="px-4 py-3 text-sm text-slate-500">
                    Flask API not reachable.
                    Start the server to load models.
                  </p>
                ) : (
                  models.map(model => (
                    <button
                      key={model.id}
                      onClick={() => {
                        setSelectedModel(model);
                        setShowModelPicker(false);
                      }}
                      className={`w-full flex items-center
                        justify-between px-4 py-3 text-left
                        hover:bg-slate-700 transition-colors
                        text-sm border-b border-slate-700/50
                        last:border-0
                        ${selectedModel?.id === model.id
                          ? 'text-purple-400 bg-purple-500/5'
                          : 'text-slate-300'
                        }`}
                    >
                      <span>{model.display}</span>
                      {model.is_default && (
                        <span className="text-xs text-blue-400
                                        bg-blue-500/10
                                        border border-blue-500/30
                                        px-2 py-0.5 rounded-full">
                          Best Model
                        </span>
                      )}
                    </button>
                  ))
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      )}

      {/* Sample transaction selector  */}
      {!result && (
        <div className="mb-4">
          <button
            onClick={() => setShowSelector(s => !s)}
            className="w-full flex items-center
                       justify-between px-4 py-3
                       bg-slate-800/60 border border-slate-700/50
                       rounded-xl hover:border-blue-500/50
                       transition-all text-slate-300
                       hover:text-white"
          >
            <div className="flex items-center gap-2">
              <Database size={16} className="text-blue-400" />
              <span className="text-sm font-medium">
                {selectedSample
                  ? `Loaded: ${selectedSample.description}`
                  : 'Load real test transaction (10 fraud + 10 legitimate)'
                }
              </span>
            </div>
            <div className="flex items-center gap-2">
              {selectedSample && (
                <span className={`text-xs px-2 py-0.5
                  rounded-full font-semibold border
                  ${selectedSample.label === 'FRAUD'
                    ? 'text-red-400 bg-red-500/10 border-red-500/30'
                    : 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30'
                  }`}>
                  {selectedSample.label}
                </span>
              )}
              <ChevronDown
                size={16}
                className={`transition-transform
                  ${showSelector ? 'rotate-180' : ''}`}
              />
            </div>
          </button>

          <AnimatePresence>
            {showSelector && (
              <motion.div
                initial={{ opacity:0, y:-8 }}
                animate={{ opacity:1, y:0 }}
                exit={{ opacity:0, y:-8 }}
                transition={{ duration:0.2 }}
                className="mt-2 bg-slate-800 border
                           border-slate-700 rounded-xl
                           overflow-hidden shadow-2xl"
              >
                <div className="grid grid-cols-2
                               divide-x divide-slate-700">

                  {/* Fraud samples */}
                  <div className="p-3">
                    <p className="text-xs font-semibold
                                 text-red-400 uppercase
                                 tracking-wider mb-2 px-1">
                      Fraud Transactions
                    </p>
                    {fraudSamples.map(sample => (
                      <button
                        key={sample.id}
                        onClick={() => loadSample(sample)}
                        className="w-full text-left px-3 py-2
                                   rounded-lg hover:bg-red-500/10
                                   transition-colors text-sm
                                   text-slate-300
                                   hover:text-red-300 mb-1"
                      >
                        <span className="block font-mono text-xs">
                          {sample.description}
                        </span>
                        <span className="text-xs text-slate-500">
                          True label: FRAUD
                        </span>
                      </button>
                    ))}
                  </div>

                  {/* Legitimate samples */}
                  <div className="p-3">
                    <p className="text-xs font-semibold
                                 text-emerald-400 uppercase
                                 tracking-wider mb-2 px-1">
                      Legitimate Transactions
                    </p>
                    {legitSamples.map(sample => (
                      <button
                        key={sample.id}
                        onClick={() => loadSample(sample)}
                        className="w-full text-left px-3 py-2
                                   rounded-lg
                                   hover:bg-emerald-500/10
                                   transition-colors text-sm
                                   text-slate-300
                                   hover:text-emerald-300 mb-1"
                      >
                        <span className="block font-mono text-xs">
                          {sample.description}
                        </span>
                        <span className="text-xs text-slate-500">
                          True label: LEGITIMATE
                        </span>
                      </button>
                    ))}
                  </div>
                </div>

                {selectedSample && (
                  <div className="border-t border-slate-700 p-2">
                    <button
                      onClick={clearSample}
                      className="w-full text-xs text-slate-500
                                 hover:text-slate-300 py-1
                                 transition-colors"
                    >
                      Clear enter values manually
                    </button>
                  </div>
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      )}

      {/* Main form / result card  */}
      <div className="bg-slate-900 border border-slate-700/50
                     rounded-2xl shadow-2xl overflow-hidden">

        {/* Progress bar */}
        {!result && (
          <div className="h-1 bg-slate-800">
            <motion.div
              className="h-full bg-blue-500"
              animate={{ width:`${progress}%` }}
              transition={{ duration:0.3 }}
            />
          </div>
        )}

        <div className="p-8">
          <AnimatePresence mode="wait">

            {/* Result view  */}
            {result ? (
              <motion.div
                key="result"
                variants={resultVariants}
                initial="hidden"
                animate="visible"
                className="text-center"
              >
                {/* Ground truth banner */}
                {selectedSample && (
                  <div className="mb-6 px-4 py-2 bg-slate-800
                                 border border-slate-600
                                 rounded-xl text-sm text-slate-400">
                    Ground truth:{' '}
                    <span className={`font-bold
                      ${selectedSample.label === 'FRAUD'
                        ? 'text-red-400' : 'text-emerald-400'
                      }`}>
                      {selectedSample.label}
                    </span>
                    {' '}—{' '}
                    {result.decision === selectedSample.label
                      ? <span className="text-emerald-400">
                          Correct ✓
                        </span>
                      : <span className="text-orange-400">
                          Incorrect ✗
                        </span>
                    }
                  </div>
                )}

                {/* Model used badge */}
                <div className="mb-4">
                  <span className="text-xs text-slate-500
                                  bg-slate-800 px-3 py-1
                                  rounded-full border
                                  border-slate-700">
                    Scored by: {result.model_used}
                  </span>
                </div>

                {/* Decision icon */}
                <div className={`inline-flex p-5 rounded-full mb-6
                  ${result.decision === 'FRAUD'
                    ? 'bg-red-500/10 border border-red-500/30'
                    : 'bg-emerald-500/10 border border-emerald-500/30'
                  }`}>
                  {result.decision === 'FRAUD'
                    ? <AlertOctagon className="text-red-400"
                                    size={52} />
                    : <ShieldCheck className="text-emerald-400"
                                   size={52} />
                  }
                </div>

                {/* Decision text */}
                <h2 className={`text-5xl font-black
                               tracking-tight mb-2
                  ${result.decision === 'FRAUD'
                    ? 'text-red-400' : 'text-emerald-400'
                  }`}>
                  {result.decision}
                </h2>

                {/* Confidence tier badge */}
                {(() => {
                  const tier =
                    TIER_CONFIG[result.confidence_tier];
                  return (
                    <span className={`inline-block px-4 py-1
                      rounded-full text-sm font-semibold
                      border mb-8
                      ${tier.color} ${tier.bg} ${tier.border}`}>
                      {result.confidence_tier} CONFIDENCE
                    </span>
                  );
                })()}

                {/* Metrics grid */}
                <div className="grid grid-cols-3 gap-4 mb-8">
                  {[
                    {
                      label: 'Fraud Probability',
                      value: `${result.fraud_probability}%`,
                      color: result.decision === 'FRAUD'
                        ? 'text-red-400' : 'text-emerald-400'
                    },
                    {
                      label: 'Anomaly Score',
                      value: `${result.anomaly_score}%`,
                      color: 'text-blue-400'
                    },
                    {
                      label: 'Threshold',
                      value: `${result.threshold_used}%`,
                      color: 'text-slate-400'
                    }
                  ].map(({ label, value, color }) => (
                    <div key={label}
                      className="bg-slate-800/60 border
                                 border-slate-700/50
                                 rounded-xl p-4">
                      <p className="text-xs text-slate-500
                                   uppercase tracking-wider mb-1">
                        {label}
                      </p>
                      <p className={`text-2xl font-mono
                                    font-bold ${color}`}>
                        {value}
                      </p>
                    </div>
                  ))}
                </div>

                {/* Key feature values */}
                <div className="bg-slate-800/40 border
                               border-slate-700/50 rounded-xl
                               p-4 mb-8 text-left">
                  <p className="text-xs text-slate-500 uppercase
                               tracking-wider mb-3">
                    Key Feature Values (Top 4 Predictors)
                  </p>
                  <div className="grid grid-cols-2 gap-2">
                    {['V14','V17','V4','V12'].map(f => (
                      <div key={f}
                        className="flex justify-between
                                   items-center bg-slate-900/60
                                   rounded-lg px-3 py-2">
                        <span className="text-slate-400 text-sm
                                        font-mono">{f}</span>
                        <span className="text-slate-200 text-sm
                                        font-mono">
                          {parseFloat(
                            result.raw_input[f]
                          ).toFixed(4)}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Reset button */}
                <button
                  onClick={reset}
                  className="flex items-center gap-2 mx-auto
                             px-6 py-3 bg-slate-800
                             hover:bg-slate-700 border
                             border-slate-600 rounded-xl
                             transition-all text-slate-300
                             hover:text-white"
                >
                  <RefreshCw size={16} />
                  New Prediction
                </button>
              </motion.div>

            ) : (
              /* Form steps  */
              <motion.div
                key={`step-${step}`}
                variants={slideVariants}
                initial="hidden"
                animate="visible"
                exit="exit"
              >
                {/* Step header */}
                <div className="mb-6">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs text-blue-400
                                    font-semibold uppercase
                                    tracking-wider">
                      Step {step + 1} of {totalSteps}
                    </span>
                    {selectedSample && (
                      <span className={`text-xs px-2 py-0.5
                        rounded-full font-semibold border
                        ${selectedSample.label === 'FRAUD'
                          ? 'text-red-400 bg-red-500/10 border-red-500/30'
                          : 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30'
                        }`}>
                        {selectedSample.description}
                      </span>
                    )}
                  </div>
                  <h2 className="text-xl font-bold">
                    {STEP_CONFIG[step].title}
                  </h2>
                  <p className="text-slate-400 text-sm mt-1">
                    {STEP_CONFIG[step].subtitle}
                  </p>
                </div>

                {/* Input grid */}
                <div className="grid grid-cols-2 gap-3 mb-8">
                  {STEP_CONFIG[step].fields.map(field => (
                    <div key={field}>
                      <label className="block text-xs
                                       text-slate-400 mb-1
                                       font-medium">
                        {field === 'Time'   ? 'Time (seconds)'
                        : field === 'Amount' ? 'Amount (€)'
                        : field}
                      </label>
                      <input
                        type="number"
                        name={field}
                        value={formData[field]}
                        onChange={handleChange}
                        step="any"
                        placeholder="0.000000"
                        className="w-full bg-slate-800 border
                                   border-slate-700 rounded-lg
                                   px-3 py-2.5 text-sm font-mono
                                   text-slate-100
                                   placeholder-slate-600
                                   focus:outline-none
                                   focus:border-blue-500
                                   focus:ring-1
                                   focus:ring-blue-500/50
                                   transition-colors"
                      />
                    </div>
                  ))}
                </div>

                {/* Error */}
                {error && (
                  <div className="mb-4 px-4 py-3 bg-red-500/10
                                 border border-red-500/30
                                 rounded-xl text-red-400 text-sm">
                    {error}
                  </div>
                )}

                {/* Navigation */}
                <div className="flex gap-3">
                  {step > 0 && (
                    <button
                      onClick={back}
                      className="flex items-center gap-2
                                 px-5 py-3 bg-slate-800
                                 hover:bg-slate-700 border
                                 border-slate-600 rounded-xl
                                 transition-all text-slate-300"
                    >
                      <ArrowLeft size={16} />
                      Back
                    </button>
                  )}
                  <button
                    onClick={next}
                    disabled={loading}
                    className="flex-1 flex items-center
                               justify-center gap-2 py-3
                               bg-blue-600 hover:bg-blue-500
                               disabled:opacity-50
                               disabled:cursor-not-allowed
                               rounded-xl font-semibold
                               transition-all"
                  >
                    {loading ? (
                      <>
                        <Loader2 size={18}
                          className="animate-spin" />
                        Analysing...
                      </>
                    ) : isLastStep ? (
                      <>
                        <ShieldCheck size={18} />
                        Analyse Transaction
                      </>
                    ) : (
                      <>
                        Continue
                        <ArrowRight size={18} />
                      </>
                    )}
                  </button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>

      {/* Footer */}
      <p className="text-center text-xs text-slate-700 mt-6">
        AutoGluon WeightedEnsemble · Isolation Forest ·
        AUC-ROC 0.9610
      </p>
    </div>
  );
}